import { mkdtempSync, mkdirSync, copyFileSync, utimesSync, writeFileSync } from 'node:fs';
import { homedir, tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import {
  claudeRoot,
  LABEL_SCAN_BYTES,
  listSessions,
  MAX_WORKFLOW_BYTES,
  readAgentMeta,
  readWorkflowRun,
  sessionLabel,
  subagentFiles,
  workflowRunFiles,
} from '../server/sessions';

it('discovers sessions and subagent files', () => {
  const root = mkdtempSync(join(tmpdir(), 'rt-root-'));
  const slugDir = join(root, 'projects', 'demo');
  mkdirSync(join(slugDir, 'fix-sess', 'subagents'), { recursive: true });
  copyFileSync('fixtures/main-session.jsonl', join(slugDir, 'fix-sess.jsonl'));
  copyFileSync('fixtures/agent-abc123.jsonl', join(slugDir, 'fix-sess', 'subagents', 'agent-abc123.jsonl'));
  const s = listSessions(root);
  expect(s).toHaveLength(1);
  expect(s[0].sessionId).toBe('fix-sess');
  const subs = subagentFiles(root, 'demo', 'fix-sess');
  expect(subs).toEqual([expect.objectContaining({ agentId: 'abc123' })]);
});

describe('listSessions edge cases', () => {
  it('returns an empty list when projects/ is missing', () => {
    const root = mkdtempSync(join(tmpdir(), 'rt-root-'));
    expect(listSessions(root)).toEqual([]);
  });

  it('ignores non-.jsonl entries at the top level of a slug dir', () => {
    const root = mkdtempSync(join(tmpdir(), 'rt-root-'));
    const slugDir = join(root, 'projects', 'demo');
    // fix-sess/ (a directory, from the subagents scaffold below) and notes.txt must both
    // be skipped — only *.jsonl files at this level count as sessions.
    mkdirSync(join(slugDir, 'fix-sess', 'subagents'), { recursive: true });
    copyFileSync('fixtures/main-session.jsonl', join(slugDir, 'fix-sess.jsonl'));
    writeFileSync(join(slugDir, 'notes.txt'), 'not a session');
    const s = listSessions(root);
    expect(s).toHaveLength(1);
    expect(s[0]).toEqual(
      expect.objectContaining({ sessionId: 'fix-sess', slug: 'demo', file: join(slugDir, 'fix-sess.jsonl') }),
    );
    expect(typeof s[0].mtime).toBe('number');
  });
});

describe('subagentFiles edge cases', () => {
  it('returns an empty list when subagents/ is missing', () => {
    const root = mkdtempSync(join(tmpdir(), 'rt-root-'));
    mkdirSync(join(root, 'projects', 'demo', 'fix-sess'), { recursive: true });
    expect(subagentFiles(root, 'demo', 'fix-sess')).toEqual([]);
  });

  it('returns an empty list when the session directory does not exist at all', () => {
    const root = mkdtempSync(join(tmpdir(), 'rt-root-'));
    expect(subagentFiles(root, 'demo', 'no-such-session')).toEqual([]);
  });

  it('ignores .meta.json sidecar files, matching only agent-*.jsonl', () => {
    const root = mkdtempSync(join(tmpdir(), 'rt-root-'));
    const subagentsDir = join(root, 'projects', 'demo', 'fix-sess', 'subagents');
    mkdirSync(subagentsDir, { recursive: true });
    copyFileSync('fixtures/agent-abc123.jsonl', join(subagentsDir, 'agent-abc123.jsonl'));
    copyFileSync('fixtures/agent-abc123.meta.json', join(subagentsDir, 'agent-abc123.meta.json'));
    const subs = subagentFiles(root, 'demo', 'fix-sess');
    expect(subs).toEqual([expect.objectContaining({ agentId: 'abc123' })]);
  });
});

/**
 * What tells one session from another.
 *
 * The CLI names a session after its cwd leaf plus a counter, so six tabs opened in the same
 * directory read `dev-52`, `dev-70`, `dev-ef` — different by two hex characters and by
 * nothing a person can use. What distinguishes them is what they were asked to do.
 */
describe('sessionLabel', () => {
  const line = (body: Record<string, unknown>): string => `${JSON.stringify(body)}\n`;

  const userLine = (text: string, extra: Record<string, unknown> = {}): string =>
    line({
      type: 'user',
      timestamp: '2026-08-03T09:00:00.000Z',
      ...extra,
      message: { role: 'user', content: text },
    });

  /** One assistant line of roughly `bytes` bytes, for pushing a human turn past the scan cap. */
  const filler = (bytes: number): string =>
    line({
      type: 'assistant',
      timestamp: '2026-08-03T09:00:00.000Z',
      message: { role: 'assistant', model: 'claude-opus-5', content: [{ type: 'text', text: 'z'.repeat(bytes) }] },
    });

  const transcript = (body: string): string => {
    const dir = mkdtempSync(join(tmpdir(), 'rt-label-'));
    const file = join(dir, 'sess.jsonl');
    writeFileSync(file, body);
    return file;
  };

  it('takes the first human turn, past everything the CLI said first', () => {
    // A real session opens with the caveat, the slash-command echo the caveat is warning about,
    // its output, and a hook — four `user` lines before the human has said a word.
    const file = transcript(
      userLine('<local-command-caveat>Caveat: The messages below were generated by the user…</local-command-caveat>') +
        userLine('<command-name>/effort</command-name>\n<command-args></command-args>') +
        userLine('<local-command-stdout>Set effort level to xhigh</local-command-stdout>') +
        userLine('<user-prompt-submit-hook>ready</user-prompt-submit-hook>') +
        userLine('find the flaky test in the scheduler') +
        userLine('and then fix it'),
    );
    expect(sessionLabel(file)).toBe('find the flaky test in the scheduler');
  });

  it('says nothing at all when the session has only ever been talked at by the CLI', () => {
    // Absent is the honest answer, and it is worth showing as absent: the alternative is a tab
    // labelled with the machine's own boilerplate, which tells a person nothing they can use.
    const file = transcript(
      userLine('<local-command-caveat>Caveat: …</local-command-caveat>') +
        userLine('<system-reminder>the file was modified</system-reminder>') +
        filler(200),
    );
    expect(sessionLabel(file)).toBeUndefined();
  });

  it('never labels a session with a compaction summary', () => {
    // ~14 500 characters of the CLI's own words, written as a `user` turn. It would make every
    // long session's tab identical — and identical tabs are the problem this label exists to fix.
    const file = transcript(
      userLine('This session is being continued from a previous conversation that ran out of context. Summary: …', {
        isCompactSummary: true,
      }),
    );
    expect(sessionLabel(file)).toBeUndefined();
  });

  it('reads a human turn in the block form of a user line too', () => {
    const file = transcript(
      line({
        type: 'user',
        timestamp: '2026-08-03T09:00:00.000Z',
        message: { role: 'user', content: [{ type: 'text', text: 'ship the observer' }] },
      }),
    );
    expect(sessionLabel(file)).toBe('ship the observer');
  });

  it('stops at the byte cap rather than reading a whole transcript', () => {
    // This runs for every session on the machine on every roster sweep — 174 in one slug here —
    // so the bound is the whole design. A session whose first human turn is past it has no label,
    // which is the same answer as a session that has not been asked anything yet.
    const file = transcript(filler(LABEL_SCAN_BYTES) + userLine('too far in to be found'));
    expect(sessionLabel(file)).toBeUndefined();
  });

  it('still finds a human turn that sits just inside the cap', () => {
    // The other half of the bound: a cap that quietly stopped short would leave every session
    // unlabelled and look exactly like a session nobody has asked anything.
    const file = transcript(filler(LABEL_SCAN_BYTES / 2) + userLine('inside the cap'));
    expect(sessionLabel(file)).toBe('inside the cap');
  });

  it('clips to something a tab can hold, and says that it did', () => {
    const file = transcript(userLine(`${'a'.repeat(200)} tail`));
    const label = sessionLabel(file);
    expect(label).toHaveLength(60);
    expect(label?.endsWith('…')).toBe(true);
  });

  it('flattens a multi-line prompt onto one line', () => {
    expect(sessionLabel(transcript(userLine('rewrite the tailer\n\n- bounded reads\n- no wedging')))).toBe(
      'rewrite the tailer - bounded reads - no wedging',
    );
  });

  it('redacts it — this is user prose about to cross a socket', () => {
    expect(sessionLabel(transcript(userLine('connect with DB_PASSWORD=hunter2 and check')))).toBe(
      'connect with DB_PASSWORD=*** and check',
    );
  });

  it('returns undefined rather than throwing on a file that is not there', () => {
    expect(sessionLabel(join(tmpdir(), 'rt-label-nothing', 'gone.jsonl'))).toBeUndefined();
  });

  it('steps over a half-written line instead of giving up on the file', () => {
    // `~/.claude` is being appended to by another process, so a torn last line is routine.
    const file = transcript(`{"type":"assistant","message":\n${userLine('the real prompt')}`);
    expect(sessionLabel(file)).toBe('the real prompt');
  });
});

/**
 * The sidecar is the only place a depth-2 agent's parent is written down in full.
 *
 * `toolUseId` is the usual link, and it only resolves while the parent's `Task` call is still in
 * the client's store — trim that line past the message cap and the grandchild re-roots at `main`,
 * which draws the wrong tree and dims the wrong half of the room. 79 of the 2 105 sidecars on this
 * machine carry `parentAgentId`, every one of them at `spawnDepth: 2`, and it needs nothing else
 * to be resolvable.
 */
describe('readAgentMeta', () => {
  const withSidecar = (body: Record<string, unknown>): ReturnType<typeof readAgentMeta> => {
    const dir = mkdtempSync(join(tmpdir(), 'rt-meta-'));
    const file = join(dir, 'agent-kid.meta.json');
    writeFileSync(file, JSON.stringify(body));
    return readAgentMeta(file);
  };

  it('reads the parent agent the sidecar names', () => {
    // A real depth-2 sidecar, copied field for field.
    expect(
      withSidecar({
        agentType: 'general-purpose',
        description: 'Hunt per-colour images',
        toolUseId: 'toolu_01FPjZNbxazfmb2qDKDgxAcb',
        parentAgentId: 'a6a22154e4c0ed30d',
        spawnDepth: 2,
      }),
    ).toMatchObject({
      parentAgentId: 'a6a22154e4c0ed30d',
      parentToolUseId: 'toolu_01FPjZNbxazfmb2qDKDgxAcb',
      spawnDepth: 2,
      label: 'Hunt per-colour images',
    });
  });

  it('leaves it absent when the sidecar does not name one', () => {
    // The overwhelming majority: 2 026 of 2 105. Absent has to stay absent, because the client
    // falls back to the `toolUseId` join and an empty string is not a parent.
    expect(withSidecar({ agentType: 'Explore', spawnDepth: 1 }).parentAgentId).toBeUndefined();
  });

  it('ignores a parentAgentId that is not a string', () => {
    expect(withSidecar({ agentType: 'Explore', parentAgentId: 42 }).parentAgentId).toBeUndefined();
  });
});

/**
 * The phase record a Workflow run leaves behind.
 *
 * Measured against the 78 real runs on the machine this was written on, and every expectation
 * below is a fact taken off one of them rather than off the design spec — which described a
 * `journal.jsonl` ingestion that does not match what that file actually holds. See
 * `docs/notes/workflow-journal-findings.md`.
 */
describe('workflow runs', () => {
  /** Builds a session root with one run file under the session's own workflows directory. */
  function withRun(runId: string, body: Record<string, unknown>): { root: string; file: string } {
    const root = mkdtempSync(join(tmpdir(), 'rt-wf-'));
    const dir = join(root, 'projects', 'demo', 'fix-sess', 'workflows');
    mkdirSync(dir, { recursive: true });
    const file = join(dir, `${runId}.json`);
    writeFileSync(file, JSON.stringify(body));
    return { root, file };
  }

  const agentRow = (over: Record<string, unknown>): Record<string, unknown> => ({
    type: 'workflow_agent',
    index: 1,
    label: 'step:one',
    phaseIndex: 1,
    phaseTitle: 'One',
    agentId: 'a0000000000000001',
    state: 'done',
    queuedAt: 1_000,
    startedAt: 1_010,
    attempt: 1,
    ...over,
  });

  it('groups a run into phases, each naming the agents that belong to it', () => {
    const { file } = withRun('wf_aaaaaaaa-111', {
      runId: 'wf_aaaaaaaa-111',
      workflowName: 'nightly',
      status: 'completed',
      startTime: 1_000,
      durationMs: 500,
      phases: [{ title: 'One' }, { title: 'Two' }],
      workflowProgress: [
        { type: 'workflow_phase', index: 1, title: 'One' },
        { type: 'workflow_phase', index: 2, title: 'Two' },
        agentRow({ index: 1, agentId: 'a1', queuedAt: 1_000 }),
        agentRow({ index: 2, agentId: 'a2', queuedAt: 1_005 }),
        agentRow({ index: 3, agentId: 'a3', phaseIndex: 2, phaseTitle: 'Two', queuedAt: 2_000 }),
      ],
    });

    const run = readWorkflowRun(file);
    expect(run).toMatchObject({ workflowId: 'wf_aaaaaaaa-111', workflowName: 'nightly', status: 'completed' });
    expect(run?.phases.map((p) => p.title)).toEqual(['One', 'Two']);
    // The whole point of the event: a consumer can answer "which agents are in this phase".
    expect(run?.phases[0].agents.map((a) => a.agentId)).toEqual(['a1', 'a2']);
    expect(run?.phases[1].agents.map((a) => a.agentId)).toEqual(['a3']);
    // The end of the run, so the frame is stamped with when it happened and not when it was read.
    expect(run?.endedAt).toBe(1_500);
  });

  /**
   * The trap this test exists for.
   *
   * On a real killed run the *first* agent the runtime queued carries `phaseIndex: 2`, and the 88
   * that followed carry `phaseIndex: 1`. The declared index is a registration id, not a position
   * in time, so anything that sorts by it draws the phases in the wrong order — and the office
   * would show a run moving backwards through itself.
   */
  it('orders phases by when their agents were queued, not by the declared index', () => {
    const { file } = withRun('wf_bbbbbbbb-222', {
      runId: 'wf_bbbbbbbb-222',
      status: 'killed',
      workflowProgress: [
        { type: 'workflow_phase', index: 1, title: 'Second' },
        { type: 'workflow_phase', index: 2, title: 'First' },
        agentRow({ agentId: 'early', phaseIndex: 2, phaseTitle: 'First', queuedAt: 100 }),
        agentRow({ agentId: 'late', phaseIndex: 1, phaseTitle: 'Second', queuedAt: 900 }),
      ],
    });

    const run = readWorkflowRun(file);
    expect(run?.phases.map((p) => p.title)).toEqual(['First', 'Second']);
    // `order` is the position in time; `index` stays whatever the runtime called it.
    expect(run?.phases.map((p) => p.order)).toEqual([0, 1]);
    expect(run?.phases.map((p) => p.index)).toEqual([2, 1]);
  });

  /**
   * Top-level `phases` is a declaration written by the script author and is not always complete —
   * one real run declares a single phase while its progress rows attribute agents to two. Trusting
   * it would drop every agent of the phase it forgot to mention.
   */
  it('takes the phase roster from the progress rows, not from the declared phases array', () => {
    const { file } = withRun('wf_cccccccc-333', {
      runId: 'wf_cccccccc-333',
      status: 'killed',
      phases: [{ title: 'Declared', detail: 'the only one the author wrote down' }],
      workflowProgress: [
        { type: 'workflow_phase', index: 1, title: 'Declared' },
        { type: 'workflow_phase', index: 2, title: 'Undeclared' },
        agentRow({ agentId: 'a1', phaseIndex: 2, phaseTitle: 'Undeclared', queuedAt: 10 }),
        agentRow({ agentId: 'a2', phaseIndex: 1, phaseTitle: 'Declared', queuedAt: 20 }),
      ],
    });
    expect(readWorkflowRun(file)?.phases.map((p) => p.title)).toEqual(['Undeclared', 'Declared']);
  });

  /**
   * A phase named only by the agents in it still has to appear.
   *
   * The `workflow_phase` rows and the agents' own `phaseTitle` are two independent records of the
   * same fact, and a run that was killed before a phase was registered has the second without the
   * first. Dropping those agents would lose them from the office entirely.
   */
  it('recovers a phase that only the agent rows mention', () => {
    const { file } = withRun('wf_dddddddd-444', {
      runId: 'wf_dddddddd-444',
      status: 'failed',
      workflowProgress: [agentRow({ agentId: 'orphan', phaseIndex: 7, phaseTitle: 'Unregistered' })],
    });
    expect(readWorkflowRun(file)?.phases).toEqual([
      expect.objectContaining({ index: 7, title: 'Unregistered', order: 0 }),
    ]);
  });

  it('names the phase the run was in when it stopped, and leaves it absent once every agent finished', () => {
    const stalled = withRun('wf_eeeeeeee-555', {
      runId: 'wf_eeeeeeee-555',
      status: 'killed',
      workflowProgress: [
        agentRow({ agentId: 'a1', phaseIndex: 1, phaseTitle: 'One', state: 'done', queuedAt: 10 }),
        agentRow({ agentId: 'a2', phaseIndex: 2, phaseTitle: 'Two', state: 'progress', queuedAt: 20 }),
        agentRow({ agentId: 'a3', phaseIndex: 2, phaseTitle: 'Two', state: 'start', queuedAt: 21 }),
      ],
    });
    // `order` 1 is "Two" — where the run was when it was killed, which is the only moment this
    // artifact can describe: it is written once, when the run terminates.
    expect(readWorkflowRun(stalled.file)?.activePhase).toBe(1);

    const finished = withRun('wf_ffffffff-666', {
      runId: 'wf_ffffffff-666',
      status: 'completed',
      workflowProgress: [
        agentRow({ agentId: 'a1', state: 'done' }),
        agentRow({ agentId: 'a2', state: 'error', queuedAt: 20 }),
      ],
    });
    // `error` is finished, not stuck. A run where everything reached an end is in no phase at all.
    expect(readWorkflowRun(finished.file)?.activePhase).toBeUndefined();
  });

  it('refuses a file past the byte cap rather than parsing it', () => {
    const { file } = withRun('wf_99999999-777', {
      runId: 'wf_99999999-777',
      status: 'completed',
      // Real run files reach 1.4 MB, almost all of it prompt and result previews. The cap is what
      // stops one pathological file from being parsed on the hub's event loop.
      script: 'x'.repeat(MAX_WORKFLOW_BYTES + 1),
      workflowProgress: [agentRow({})],
    });
    expect(readWorkflowRun(file)).toBeUndefined();
  });

  it('returns nothing for a half-written or malformed file instead of throwing', () => {
    const root = mkdtempSync(join(tmpdir(), 'rt-wf-'));
    const dir = join(root, 'projects', 'demo', 'fix-sess', 'workflows');
    mkdirSync(dir, { recursive: true });
    const torn = join(dir, 'wf_torn-888.json');
    writeFileSync(torn, '{"runId":"wf_torn-888","workflowProg');
    expect(readWorkflowRun(torn)).toBeUndefined();
    expect(readWorkflowRun(join(dir, 'wf_absent-999.json'))).toBeUndefined();
    // Valid JSON, but nothing that describes a run: no phases, no agents, so nothing to publish.
    const empty = join(dir, 'wf_empty-000.json');
    writeFileSync(empty, JSON.stringify({ runId: 'wf_empty-000', status: 'completed' }));
    expect(readWorkflowRun(empty)).toBeUndefined();
  });

  it('lists run files with a stamp that changes only when the file does', () => {
    const { root, file } = withRun('wf_aaaaaaaa-111', {
      runId: 'wf_aaaaaaaa-111',
      status: 'completed',
      workflowProgress: [agentRow({})],
    });
    const dir = join(root, 'projects', 'demo', 'fix-sess', 'workflows');
    // Neither of these is a run file, and both sit in the same directory on a real machine.
    writeFileSync(join(dir, 'notes.txt'), 'not a run');
    mkdirSync(join(dir, 'wf_a-dir.json'), { recursive: true });

    const first = workflowRunFiles(root, 'demo', 'fix-sess');
    expect(first.map((r) => r.file)).toEqual([file]);
    expect(workflowRunFiles(root, 'demo', 'fix-sess')[0].stamp).toBe(first[0].stamp);

    // The stamp is (mtime, size), so a rewrite that changes neither would be missed — which is
    // safe here precisely because these files are written exactly once and never edited.
    writeFileSync(file, JSON.stringify({ runId: 'wf_aaaaaaaa-111', status: 'failed', workflowProgress: [] }));
    const later = new Date(Date.now() + 5_000);
    utimesSync(file, later, later);
    expect(workflowRunFiles(root, 'demo', 'fix-sess')[0].stamp).not.toBe(first[0].stamp);
  });

  it('returns an empty list when the session has never run a workflow', () => {
    const root = mkdtempSync(join(tmpdir(), 'rt-wf-'));
    mkdirSync(join(root, 'projects', 'demo', 'fix-sess'), { recursive: true });
    expect(workflowRunFiles(root, 'demo', 'fix-sess')).toEqual([]);
  });
});

describe('claudeRoot', () => {
  it('honors ROUNDTABLE_HOME when set', () => {
    const prev = process.env.ROUNDTABLE_HOME;
    const custom = join(tmpdir(), 'rt-custom-home');
    process.env.ROUNDTABLE_HOME = custom;
    try {
      expect(claudeRoot()).toBe(custom);
    } finally {
      if (prev === undefined) delete process.env.ROUNDTABLE_HOME;
      else process.env.ROUNDTABLE_HOME = prev;
    }
  });

  it('falls back to ~/.claude when ROUNDTABLE_HOME is unset', () => {
    const prev = process.env.ROUNDTABLE_HOME;
    delete process.env.ROUNDTABLE_HOME;
    try {
      expect(claudeRoot()).toBe(join(homedir(), '.claude'));
    } finally {
      if (prev !== undefined) process.env.ROUNDTABLE_HOME = prev;
    }
  });
});
